services:
  - type: web
    name: game-reviews-api
    runtime: docker
    plan: free
    healthCheckPath: /swagger/index.html
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: game-reviews-db
          property: connectionString
      - key: JWT_SECRET
        sync: false

databases:
  - name: game-reviews-db
    dbName: game_reviews
    user: postgres
    plan: free
    postgresVersion: 18
