
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';
SET default_table_access_method = heap;

-- Table: Genres
CREATE TABLE public."Genres" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL
);

ALTER TABLE public."Genres" OWNER TO postgres;

ALTER TABLE public."Genres" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Genres_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Table: Games
CREATE TABLE public."Games" (
    "Id" integer NOT NULL,
    "Title" text NOT NULL,
    "Description" text NOT NULL,
    "ImageUrl" text NOT NULL,
    "GenreId" integer NOT NULL
);

ALTER TABLE public."Games" OWNER TO postgres;

ALTER TABLE public."Games" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Games_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Table: Users
CREATE TABLE public."Users" (
    "Id" text NOT NULL,
    "Username" text NOT NULL,
    "PasswordHash" text NOT NULL,
    "Role" text NOT NULL
);

ALTER TABLE public."Users" OWNER TO postgres;

-- Table: Reviews
CREATE TABLE public."Reviews" (
    "Id" integer NOT NULL,
    "Rating" integer NOT NULL,
    "Comment" text NOT NULL,
    "GameId" integer NOT NULL,
    "UserId" integer NOT NULL
);

ALTER TABLE public."Reviews" OWNER TO postgres;

ALTER TABLE public."Reviews" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Reviews_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Primary Keys
ALTER TABLE ONLY public."Genres" ADD CONSTRAINT "PK_Genres" PRIMARY KEY ("Id");
ALTER TABLE ONLY public."Games" ADD CONSTRAINT "PK_Games" PRIMARY KEY ("Id");
ALTER TABLE ONLY public."Users" ADD CONSTRAINT "PK_Users" PRIMARY KEY ("Id");
ALTER TABLE ONLY public."Reviews" ADD CONSTRAINT "PK_Reviews" PRIMARY KEY ("Id");

-- Foreign Keys
ALTER TABLE ONLY public."Games"
    ADD CONSTRAINT "FK_Games_Genres_GenreId" FOREIGN KEY ("GenreId") REFERENCES public."Genres"("Id") ON DELETE CASCADE;

ALTER TABLE ONLY public."Reviews"
    ADD CONSTRAINT "FK_Reviews_Games_GameId" FOREIGN KEY ("GameId") REFERENCES public."Games"("Id") ON DELETE CASCADE;

-- Indexes
CREATE INDEX "IX_Games_GenreId" ON public."Games" USING btree ("GenreId");
CREATE INDEX "IX_Reviews_GameId" ON public."Reviews" USING btree ("GameId");


